#!/bin/sh
# NRadio C8 (WT9104 / C8-688) 首次启动默认值
uci -q batch <<-EOF
	set system.@system[0].hostname='C8'
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	set network.lan.ipaddr='192.168.66.1'
	set network.lan.netmask='255.255.255.0'
	set network.lan.delegate='1'
	set dhcp.lan.leasetime='12h'
	# LAN 侧没有可用的 IPv6 上游（模块不下发 PD），过滤 AAAA 避免客户端解析到不可达地址
	set dhcp.@dnsmasq[0].filter_aaaa='1'
	# 固定中文界面（default-settings 默认是 auto，跟随浏览器）
	set luci.main.lang='zh_cn'
	commit system
	commit network
	commit dhcp
	commit luci
EOF

exit 0
